"""create tracker tables

Revision ID: 5b9bcb7a5474
Revises:
Create Date: 2026-07-24 21:27:00.304795
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5b9bcb7a5474"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_accounts",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "asset",
                "liability",
                name="account_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("include_in_net_worth", sa.Boolean(), nullable=False),
        sa.Column("is_savings", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_savings OR account_type = 'asset'",
            name=op.f("ck_financial_accounts_savings_account_is_asset"),
        ),
        sa.CheckConstraint(
            "balance >= 0", name=op.f("ck_financial_accounts_balance_nonnegative")
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_financial_accounts_currency_three_chars"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_accounts")),
        sa.UniqueConstraint("name", "currency", name="uq_account_name_currency"),
    )
    op.create_table(
        "financial_transactions",
        sa.Column(
            "kind",
            sa.Enum(
                "income",
                "expense",
                name="financial_transaction_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_financial_transactions_amount_positive")
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_financial_transactions_currency_three_chars"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_transactions")),
    )
    op.create_index(
        op.f("ix_financial_transactions_category"),
        "financial_transactions",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_financial_transactions_currency_occurred_on",
        "financial_transactions",
        ["currency", "occurred_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_kind"),
        "financial_transactions",
        ["kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_occurred_on"),
        "financial_transactions",
        ["occurred_on"],
        unique=False,
    )
    op.create_table(
        "monthly_budgets",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column("limit_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_monthly_budgets_currency_three_chars")
        ),
        sa.CheckConstraint(
            "limit_amount > 0", name=op.f("ck_monthly_budgets_limit_amount_positive")
        ),
        sa.CheckConstraint(
            "month >= 1 AND month <= 12", name=op.f("ck_monthly_budgets_month_valid")
        ),
        sa.CheckConstraint(
            "year >= 1 AND year <= 9999", name=op.f("ck_monthly_budgets_year_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monthly_budgets")),
        sa.UniqueConstraint(
            "year",
            "month",
            "category",
            "currency",
            name="uq_monthly_budgets_period_category_currency",
        ),
    )
    op.create_index(
        "ix_monthly_budgets_period_currency",
        "monthly_budgets",
        ["year", "month", "currency"],
        unique=False,
    )
    op.create_table(
        "net_worth_snapshots",
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assets", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("liabilities", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "assets >= 0", name=op.f("ck_net_worth_snapshots_assets_nonnegative")
        ),
        sa.CheckConstraint(
            "liabilities >= 0",
            name=op.f("ck_net_worth_snapshots_liabilities_nonnegative"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_net_worth_snapshots_currency_three_chars"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_net_worth_snapshots")),
    )
    op.create_index(
        op.f("ix_net_worth_snapshots_recorded_at"),
        "net_worth_snapshots",
        ["recorded_at"],
        unique=False,
    )
    op.create_table(
        "nutrition_logs",
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("calorie_target", sa.Integer(), nullable=True),
        sa.Column("protein_grams", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("carbs_grams", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("fat_grams", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "calorie_target IS NULL OR calorie_target > 0",
            name=op.f("ck_nutrition_logs_calorie_target_positive"),
        ),
        sa.CheckConstraint(
            "calories >= 0", name=op.f("ck_nutrition_logs_calories_nonnegative")
        ),
        sa.CheckConstraint(
            "carbs_grams IS NULL OR carbs_grams >= 0",
            name=op.f("ck_nutrition_logs_carbs_grams_nonnegative"),
        ),
        sa.CheckConstraint(
            "fat_grams IS NULL OR fat_grams >= 0",
            name=op.f("ck_nutrition_logs_fat_grams_nonnegative"),
        ),
        sa.CheckConstraint(
            "protein_grams IS NULL OR protein_grams >= 0",
            name=op.f("ck_nutrition_logs_protein_grams_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nutrition_logs")),
        sa.UniqueConstraint("recorded_on", name="uq_nutrition_log_recorded_on"),
    )
    op.create_table(
        "savings_goals",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_amount >= 0",
            name=op.f("ck_savings_goals_current_amount_nonnegative"),
        ),
        sa.CheckConstraint(
            "target_amount > 0", name=op.f("ck_savings_goals_target_amount_positive")
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_savings_goals_currency_three_chars"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_savings_goals")),
        sa.UniqueConstraint("name", "currency", name="uq_savings_goal_name_currency"),
    )
    op.create_table(
        "weight_entries",
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("body_fat_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "body_fat_percent IS NULL OR "
            "(body_fat_percent >= 0 AND body_fat_percent <= 100)",
            name=op.f("ck_weight_entries_body_fat_percent_range"),
        ),
        sa.CheckConstraint(
            "weight_kg > 0", name=op.f("ck_weight_entries_weight_kg_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weight_entries")),
        sa.UniqueConstraint("recorded_on", name="uq_weight_entry_recorded_on"),
    )
    op.create_table(
        "workouts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes > 0",
            name=op.f("ck_workouts_duration_minutes_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workouts")),
    )
    op.create_index(
        "ix_workouts_performed_at_id", "workouts", ["performed_at", "id"], unique=False
    )
    op.create_table(
        "workout_sets",
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise", sa.String(length=200), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("distance_km", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "distance_km IS NULL OR distance_km >= 0",
            name=op.f("ck_workout_sets_distance_km_nonnegative"),
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name=op.f("ck_workout_sets_duration_seconds_nonnegative"),
        ),
        sa.CheckConstraint(
            "reps IS NOT NULL OR weight_kg IS NOT NULL OR "
            "distance_km IS NOT NULL OR duration_seconds IS NOT NULL",
            name=op.f("ck_workout_sets_metric_present"),
        ),
        sa.CheckConstraint(
            "reps IS NULL OR reps >= 0", name=op.f("ck_workout_sets_reps_nonnegative")
        ),
        sa.CheckConstraint(
            "set_number > 0", name=op.f("ck_workout_sets_set_number_positive")
        ),
        sa.CheckConstraint(
            "weight_kg IS NULL OR weight_kg >= 0",
            name=op.f("ck_workout_sets_weight_kg_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_workout_sets_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workout_sets")),
        sa.UniqueConstraint(
            "workout_id",
            "exercise",
            "set_number",
            name="uq_workout_sets_workout_exercise_number",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_sets")
    op.drop_index("ix_workouts_performed_at_id", table_name="workouts")
    op.drop_table("workouts")
    op.drop_table("weight_entries")
    op.drop_table("savings_goals")
    op.drop_table("nutrition_logs")
    op.drop_index(
        op.f("ix_net_worth_snapshots_recorded_at"), table_name="net_worth_snapshots"
    )
    op.drop_table("net_worth_snapshots")
    op.drop_index("ix_monthly_budgets_period_currency", table_name="monthly_budgets")
    op.drop_table("monthly_budgets")
    op.drop_index(
        op.f("ix_financial_transactions_occurred_on"),
        table_name="financial_transactions",
    )
    op.drop_index(
        op.f("ix_financial_transactions_kind"), table_name="financial_transactions"
    )
    op.drop_index(
        "ix_financial_transactions_currency_occurred_on",
        table_name="financial_transactions",
    )
    op.drop_index(
        op.f("ix_financial_transactions_category"), table_name="financial_transactions"
    )
    op.drop_table("financial_transactions")
    op.drop_table("financial_accounts")
    # ### end Alembic commands ###
